### ISSUE TITLE
Status Code: 405 Method Not Allowed

### ISSUE THREAD

**Issue by songololo** [graphql-python/sanic-graphql#3]
I am trying to use `sanic-graphql` but am encountering a `Status Code:405 Method Not Allowed` error.

The `<url>/graphql` endpoint (graphiql) works fine. However, when trying to use the endpoint from an apollo-client website then I encounter the above-mentioned Status Code 405 error when the browser attempts an `OPTION` preflight request.

This is presumably somehow related to the `sanic` documentation for [Class-Based Views](http://sanic.readthedocs.io/en/latest/sanic/class_based_views.html) which states that if the the class based view does not contain the request method (in this case the `OPTION` preflight request), then a `405: Method not allowed` error is returned.

Is there some way to resolve this?

Thanks.

**Comment by grazor** [comment]
Hi @shongololo!

Thanks for your report! This issue is indeed caused by sanic not supporting CORS and thus ignoring preflight requests.

I've created a workaround for this requests. Could you please check if it works for you? You need to clone this repo, switch to ``fix/preflight`` branch and install it to new virtual environment. Assuming your venv is active:
```bash
git clone git@github.com:graphql-python/sanic-graphql.git
cd sanic-graphql
git checkout fix/preflight
python setup.py install
```

**Comment by songololo** [comment]
@grazor yes, it works now! Thank you very much. I'll use the fix/preflight branch until this is released via pip.

**Comment by grazor** [comment]
@shongololo great! I've updated pypi package.
